// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAciY5zBU3NHZYfU5vZ48LihZAq_s-brxU',
    appId: '1:1002443824199:web:253de938e64791732ae562',
    messagingSenderId: '1002443824199',
    projectId: 'pocketplans-cca04',
    authDomain: 'pocketplans-cca04.firebaseapp.com',
    storageBucket: 'pocketplans-cca04.firebasestorage.app',
    measurementId: 'G-HZCFG3FMCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwp313YpyJErY-k-n6LkEJd1kGQWUoYE0',
    appId: '1:1002443824199:android:c0aeb6ef1a03106e2ae562',
    messagingSenderId: '1002443824199',
    projectId: 'pocketplans-cca04',
    storageBucket: 'pocketplans-cca04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_Gm9gx5qRW3T0OaB4ZDK0YSPHZzYwqo',
    appId: '1:1002443824199:ios:1633bed73e7d39242ae562',
    messagingSenderId: '1002443824199',
    projectId: 'pocketplans-cca04',
    storageBucket: 'pocketplans-cca04.firebasestorage.app',
    androidClientId: '1002443824199-l0hgfjbb5iul1913pinq4l9oglhj6884.apps.googleusercontent.com',
    iosClientId: '1002443824199-5omjsq1mfk924f7jmng5hiskp9ir05m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketplans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_Gm9gx5qRW3T0OaB4ZDK0YSPHZzYwqo',
    appId: '1:1002443824199:ios:1633bed73e7d39242ae562',
    messagingSenderId: '1002443824199',
    projectId: 'pocketplans-cca04',
    storageBucket: 'pocketplans-cca04.firebasestorage.app',
    androidClientId: '1002443824199-l0hgfjbb5iul1913pinq4l9oglhj6884.apps.googleusercontent.com',
    iosClientId: '1002443824199-5omjsq1mfk924f7jmng5hiskp9ir05m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketplans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAciY5zBU3NHZYfU5vZ48LihZAq_s-brxU',
    appId: '1:1002443824199:web:253de938e64791732ae562',
    messagingSenderId: '1002443824199',
    projectId: 'pocketplans-cca04',
    authDomain: 'pocketplans-cca04.firebaseapp.com',
    storageBucket: 'pocketplans-cca04.firebasestorage.app',
    measurementId: 'G-HZCFG3FMCM',
  );

}